### ISSUE TITLE
Failed build with h264

### ISSUE THREAD

**Issue by ilpyoung** [crow-misia/libwebrtc-bin#12]
Hi
The build ended with the following message during completion of the build.
"Exception: Missing licenses for following third_party targets: openh264, ffmpeg"

How can I put a license?

**Comment by crow-misia** [comment]
@ilpyoung
I can't reply because I have no information.

**Comment by ilpyoung** [comment]
OK, I found generated_licence file 
After entering some commands, it works normally.

But another question, Do you happen to know why the WebRTC kNV12 videoType is gone?

**Comment by crow-misia** [comment]
@ilpyoung 
I don't known it.
Please check code history of libwebrtc.

I'm not WebRTC's support center.

**Comment by ilpyoung** [comment]
okay
Thx for reply
