### ISSUE TITLE
question: How to compile dynamic link library?

### ISSUE THREAD

**Issue by jetamie** [crow-misia/libwebrtc-bin#14]

**Comment by crow-misia** [comment]
@jetamie 
I haven't tried it, but I suspect it is the is_component_build option.
I don't know any more than this about that.

**Comment by jetamie** [comment]
@crow-misia
There is only one static library inside the release

**Comment by jetamie** [comment]
@crow-misia 
Can you help try this is_component_build parameter option? I have been failing because of network problems here, thank you!

**Comment by crow-misia** [comment]
Unfortunately, I cannot help you.
Because trial and error requires a lot of time.
