### ISSUE TITLE
How to compile brwetc demo？

### ISSUE THREAD

**Issue by superHHD** [crow-misia/libwebrtc-bin#18]
How to use libwebrtc.a to compile the webrtc demo? I compile the demo in webrtc peerconnection and prompt that the undefined function leads to compilation failure.For example “ undefined reference to `absl::SetProgramUsageMessage(absl::string_view)''”.The compilation command I use is“g++ data_socket.cc main.cc peer_channel.cc utils.cc libwebrtc.a  -I ../include  -I ../include/third_party/abseil-cpp/ -DWEBRTC_POSIX  -lpthread -ldl”

**Comment by crow-misia** [comment]
If you build webrtc examples, it is Better to do it with gn.
Also, libwebrtc.a does not include most of the absl functions, including "SetProgramUsageMessage".
You can check nm to see which functions are included.
