### ISSUE TITLE
Unresolved dependencies to  ijar while building android on Mac OSX

### ISSUE THREAD

**Issue by qing-wang** [crow-misia/libwebrtc-bin#20]
Got a lot of errors such as: 

INFO:root:Building: armeabi-v7a
ERROR Unresolved dependencies.
//third_party/accessibility_test_framework:accessibility_test_framework_java__header(//build/toolchain/android:android_clang_arm)
  needs //third_party/ijar:ijar(//build/toolchain/mac:clang_x64)
//third_party/android_deps:android_arch_core_common_java__header(//build/toolchain/android:android_clang_arm)
  needs //third_party/ijar:ijar(//build/toolchain/mac:clang_x64)
//third_party/android_deps:android_arch_core_runtime_java__classes__header(//build/toolchain/android:android_clang_arm)
  needs //third_party/ijar:ijar(//build/toolchain/mac:clang_x64)
//third_party/android_deps:android_arch_lifecycle_common_java8_java__header(//build/toolchain/android:android_clang_arm)
  needs //third_party/ijar:ijar(//build/toolchain/mac:clang_x64)
//third_party/android_deps:android_arch_lifecycle_common_java__header(//build/toolchain/android:android_clang_arm)
  needs //third_party/ijar:ijar(//build/toolchain/mac:clang_x64)
//third_party/android_deps:android_arch_lifecycle_livedata_core_java__classes__header(//build/toolchain/android:android_clang_arm)
...

**Comment by crow-misia** [comment]
Use Linux PC.
