### ISSUE TITLE
Is build script broken? I cannot find pre-built libwebrtc.lib in Release and Debug folders. It only has headers files. 

### ISSUE THREAD

**Issue by shalabhawasthi** [crow-misia/libwebrtc-bin#22]
Hi,

Is the build script broken? I cannot find the libwebrtc.lib in Release and Debug folders. It only has header files. I needed pre-build binaries for the m104 build. Can you please confirm if it's a bug or an intentional change in the build script?

Thanks in advance.

**Comment by crow-misia** [comment]
Thanks for the report.
It looks like it has been broken for a long time.
It will take a while to fix it.

**Comment by shalabhawasthi** [comment]
Thanks for your quick reply. I really hope that you might be able to fix it soon. Really appreciate your efforts.

It also seems to me that header files were also out of sync from their corresponding actual WebRTC build. 
Here is the WebRTC file for your reference. You can match it with your header files.
https://github.com/webrtc-sdk/webrtc/blob/m104_release/modules/audio_device/include/audio_device.h#L24

Please correct me if it's a misunderstanding otherwise pulling mechanism is also broken.

**Comment by crow-misia** [comment]
104.5112.8.1 is released.


I compared it to the header file at https://webrtc.googlesource.com/src.git/+log/refs/branch-heads/5112 and found no differences.

There are differences in code between webrtc-sdk/webrtc and Chromium's WebRTC project.
This project uses code from Chromium's WebRTC project.

**Comment by shalabhawasthi** [comment]
Thank you very much for the quick resolution. It's my misunderstanding that this code is also based on "webrtc-sdk/webrtc" project. Thanks for the clarification. Keep up the good work. Thanks a ton.
