### ISSUE TITLE
Strage error from libboringssl.a during link

### ISSUE THREAD

**Issue by trump-7575** [crow-misia/libwebrtc-bin#23]
I tried to use both the libwebrtc and libboringssl.a at my linux ( x86_64 ) application. But the compile process stops with the following error at the last link step : 

g++ -pthread -o the_final_binary the_list_of_obj_files  lib/libboringssl.a lib/libwebrtc.a  -lrt
/usr/bin/ld: lib/libboringssl.a(lib/boringssl/bio.o): error opening thin archive member: No such file or directory
collect2: error: ld returned 1 exit status

I tried to search the error at internet but find out nothing. Did I miss some compile switch or macro ?

**Comment by crow-misia** [comment]
105.5195.0.2 has been released
libwebrtc.a includes objects used when building libwebrtc.
Please try it out.

**Comment by trump-7575** [comment]
Thanks for the update.  The new library is linked successfully :) I still have no time to try the generated binary yet because I  am working at the other projects. Good Work !
