### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Dragon-S** [crow-misia/libwebrtc-bin#24]
Hello!
I use the libwebrtc.a you compiled, but it will report an error. The error is as follows:

Undefined symbols for architecture arm64:
  "rtc::JsonValueToString(Json::Value const&)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::Send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::SendSignalingMessage(Json::Value const&, std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
  "rtc::webrtc_checks_impl::UnreachableCodeReached(char const*, int)", referenced from:
      owt::base::MediaUtils::GetAudioCodecFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mediautils.o
      owt::base::MediaUtils::GetVideoCodecFromString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mediautils.o
      owt::base::MediaUtils::AudioCodecToString(owt::base::AudioCodec const&) in mediautils.o
      owt::base::MediaUtils::VideoCodecToString(owt::base::VideoCodec const&) in mediautils.o
      owt::base::ObjcVideoCapturerFactory::Create(owt::base::LocalCameraStreamParameters const&) in OWTCameraVideoCapturer.o
      owt::base::EncodedFrameBuffer::ToI420() in customizedframescapturer.o
      owt::base::PeerConnectionDependencyFactory::CreatePeerConnectionFactoryOnCurrentThread() in peerconnectiondependencyfactory.o
      ...
  "rtc::GetIntFromJsonObject(Json::Value const&, absl::string_view, int*)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnMessageSignal(Json::Value&) in p2ppeerconnectionchannel.o
  "rtc::GetBoolFromJsonObject(Json::Value const&, absl::string_view, bool*)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::HandleRemoteCapability(Json::Value&) in p2ppeerconnectionchannel.o
  "rtc::GetValueFromJsonObject(Json::Value const&, absl::string_view, Json::Value*)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnIncomingSignalingMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::HandleRemoteCapability(Json::Value&) in p2ppeerconnectionchannel.o
  "rtc::GetStringFromJsonObject(Json::Value const&, absl::string_view, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnIncomingSignalingMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnMessageTrackSources(Json::Value&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnMessageSignal(Json::Value&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnDataChannelMessage(webrtc::DataBuffer const&) in p2ppeerconnectionchannel.o
  "Json::Value::append(Json::Value&&)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::DrainPendingStreams() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnAddStream(rtc::scoped_refptr<webrtc::MediaStreamInterface>) in p2ppeerconnectionchannel.o
  "Json::Value::append(Json::Value const&)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::DrainPendingStreams() in p2ppeerconnectionchannel.o
  "Json::Value::Value(Json::ValueType)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::SendStop(std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::SendUaInfo() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::DrainPendingStreams() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::Send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnIncomingSignalingMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::HandleRemoteCapability(Json::Value&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnAddStream(rtc::scoped_refptr<webrtc::MediaStreamInterface>) in p2ppeerconnectionchannel.o
      ...
  "Json::Value::Value(char const*)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnIceCandidate(webrtc::IceCandidateInterface const*) in p2ppeerconnectionchannel.o
  "Json::Value::Value(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::SendStop(std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::SendUaInfo() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::DrainPendingStreams() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::Send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnAddStream(rtc::scoped_refptr<webrtc::MediaStreamInterface>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnIceCandidate(webrtc::IceCandidateInterface const*) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnSetLocalSessionDescriptionSuccess() in p2ppeerconnectionchannel.o
      ...
  "Json::Value::Value(bool)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::UaInfo() in p2ppeerconnectionchannel.o
  "Json::Value::Value(int)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnIceCandidate(webrtc::IceCandidateInterface const*) in p2ppeerconnectionchannel.o
  "Json::Value::~Value()", referenced from:
      owt::p2p::P2PPeerConnectionChannel::SendStop(std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::SendUaInfo() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::DrainPendingStreams() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::Send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnIncomingSignalingMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::HandleRemoteCapability(Json::Value&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnAddStream(rtc::scoped_refptr<webrtc::MediaStreamInterface>) in p2ppeerconnectionchannel.o
      ...
  "Json::Value::operator=(Json::Value&&)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::SendStop(std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::SendUaInfo() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::DrainPendingStreams() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::Send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnAddStream(rtc::scoped_refptr<webrtc::MediaStreamInterface>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnIceCandidate(webrtc::IceCandidateInterface const*) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnSetLocalSessionDescriptionSuccess() in p2ppeerconnectionchannel.o
      ...
  "Json::Value::operator=(Json::Value const&)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::SendUaInfo() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::DrainPendingStreams() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnAddStream(rtc::scoped_refptr<webrtc::MediaStreamInterface>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnIceCandidate(webrtc::IceCandidateInterface const*) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnSetLocalSessionDescriptionSuccess() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::UaInfo() in p2ppeerconnectionchannel.o
  "Json::Value::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::SendStop(std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::SendUaInfo() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::DrainPendingStreams() in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::Send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<void ()>, std::__1::function<void (std::__1::unique_ptr<owt::base::Exception, std::__1::default_delete<owt::base::Exception> >)>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnAddStream(rtc::scoped_refptr<webrtc::MediaStreamInterface>) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnIceCandidate(webrtc::IceCandidateInterface const*) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnSetLocalSessionDescriptionSuccess() in p2ppeerconnectionchannel.o
      ...
  "Json::Value::operator[](unsigned int)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnMessageTrackSources(Json::Value&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnMessageTracksAdded(Json::Value&) in p2ppeerconnectionchannel.o
  "Json::Reader::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Json::Value&, bool)", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnIncomingSignalingMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnDataChannelMessage(webrtc::DataBuffer const&) in p2ppeerconnectionchannel.o
  "Json::Reader::Reader()", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnIncomingSignalingMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnDataChannelMessage(webrtc::DataBuffer const&) in p2ppeerconnectionchannel.o
  "Json::Value::size() const", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnMessageTrackSources(Json::Value&) in p2ppeerconnectionchannel.o
      owt::p2p::P2PPeerConnectionChannel::OnMessageTracksAdded(Json::Value&) in p2ppeerconnectionchannel.o
  "Json::Value::asString() const", referenced from:
      owt::p2p::P2PPeerConnectionChannel::OnMessageTracksAdded(Json::Value&) in p2ppeerconnectionchannel.o
ld: symbol(s) not found for architecture arm64

**Comment by crow-misia** [comment]
@Dragon-S 
Could it compile on other architectures?

jsoncpp must be obtained additionally since jsoncpp is not contained within.
