### ISSUE TITLE
Decompress error the M98 version and exit

### ISSUE THREAD

**Issue by xujingzhou** [crow-misia/libwebrtc-bin#25]
Hi, 
    Decompress error the M98 version and exit. Thanks

cmd Info:
tar xf libwebrtc-android.tar.xz

Error Info:
tar: include/build/linux/debian_sid_amd64-sysroot/usr/include/gssapi/gssapi_generic.h: Cannot create symlink to ‘../mit-krb5/gssapi/gssapi_generic.h’: Operation not supported
tar: include/build/linux/debian_sid_amd64-sysroot/usr/include/gssapi/mechglue.h: Cannot create symlink to ‘../mit-krb5/gssapi/mechglue.h’: Operation not supported
tar: include/build/linux/debian_sid_amd64-sysroot/usr/include/gssapi/gssapi_krb5.h: Cannot create symlink to ‘../mit-krb5/gssapi/gssapi_krb5.h’: Operation not supported
tar: include/build/linux/debian_sid_amd64-sysroot/usr/include/gssapi/gssapi_ext.h: Cannot create symlink to ‘../mit-krb5/gssapi/gssapi_ext.h’: Operation not supported
tar: Exiting with failure status due to previous errors

**Comment by crow-misia** [comment]
I using this version of tar and no error occurs.
It is recommended to use a linux pc as it is built on ubuntu.

> tar (GNU tar) 1.34

**Comment by xujingzhou** [comment]
I think it is symlink connection problem because I don't have directory '.. /mit-krb5/. in my machine. But I don't know how to solve the connection in the tar package

**Comment by xujingzhou** [comment]
I think it is symlink connection problem because I don't have directory '.. /mit-krb5/. in my machine. But I don't know how to solve the connection in the tar package

**Comment by crow-misia** [comment]
Please execute on a file system that supports symbolic link.
No other way.

**Comment by xujingzhou** [comment]
i will try it
