### ISSUE TITLE
tar package include directory under which .h file is how to extract from webrtc-android source code?

### ISSUE THREAD

**Issue by xujingzhou** [crow-misia/libwebrtc-bin#26]
Hi，Please tell me, tar package include directory under which .h file is how to extract from webrtc-android source code? For example, what.sh batch files are available? thanks very much！

**Comment by crow-misia** [comment]
`tar xf filename` only.

Here is to discuss the issue, not to solve your problem.
I am not your support center.

**Comment by xujingzhou** [comment]
thanks.I'll look into it

**Comment by xujingzhou** [comment]
I'm really sorry that this question confused you. What I really meant was to confirm whether cmd similar to the following was used to extract .h files from webrtc code.

#!/bin/bash
  src=`find ./ -name "*.h*"`
  echo $src
  for obj in $src
  do
      echo "cp header file $obj"
      cp --parents $obj ./include/
  done
 
  mv ./include/src/*  ./include
  rm -rf ./include/src

**Comment by crow-misia** [comment]
please see.

https://github.com/crow-misia/libwebrtc-bin/blob/716f93df6c23e50d3115526bca6b556f3ccccb03/build/common.mk#L70
