### ISSUE TITLE
Can compile x86 lib in Release lists?

### ISSUE THREAD

**Issue by fawdlstty** [crow-misia/libwebrtc-bin#4]
such as <https://blog.csdn.net/lichen18848950451/article/details/73864227>

**Comment by fawdlstty** [comment]
The Great Firewall of China blocks the Googlesource domain name, making it very difficult to compile. I failed to compile Webrtc for a long time :disappointed:

**Comment by crow-misia** [comment]
Is a linux x86 binary enough for you?
Tell me which platform it is.

**Comment by fawdlstty** [comment]
I need win7~win10 x86 suitable static link library. Thanks a lot

**Comment by crow-misia** [comment]
@fawdlstty 

I tried to create an x86 binary, but I can't release it now because the iOS build is failing.

I've added binary files to previous release, please check them out.

https://github.com/crow-misia/libwebrtc-bin/releases/download/87.4280.10.0/libwebrtc-win-x86.7z

**Comment by fawdlstty** [comment]
非常感谢，我试试
