### ISSUE TITLE
boringssl or openssl

### ISSUE THREAD

**Issue by loveCatCoder** [crow-misia/libwebrtc-bin#5]
Whether the lib library generated by the Linux version uses boringssl or openssl, I encountered a problem using libwebrtc.a in a project that uses openssl. Thank you.

**Comment by crow-misia** [comment]
This prebuilt binary is built using BoringSSL (default for libwebrtc), so it cannot be used in conjunction with OpenSSL.
Sorry.

**Comment by loveCatCoder** [comment]
Thank you for your reply. If I want to use openssl to compile webrtc, what settings need to be modified and what should I pay attention to?

**Comment by crow-misia** [comment]
Adding "rtc_build_ssl=0" to "gn gen --args" means that I'm supposed to use an external SSL library, but I don't know if it works.

Depending on version of OpenSSL, some functions of WebRTC may be disabled.
Using OpenSSL 1.1.0 or later is recommended.
