### ISSUE TITLE
Webrtc rtc::thread is not compiled

### ISSUE THREAD

**Issue by pengwang7** [crow-misia/libwebrtc-bin#6]
I use the compiled webrtc M79（libwebrtc.a）, but RTC:: thread cannot be used normally. Other components can be used.
waht should i do, i need change version?  thank you.

CMakeFiles/test.dir/src/ice_gatherer.cpp.o: In function `void rtc::Thread::Invoke<void, void>(rtc::Location const&, rtc::FunctionView<void ()>)':
/usr/local/include/webrtc/rtc_base/thread.h:335: undefined reference to `rtc::Thread::InvokeInternal(rtc::Location const&, rtc::FunctionView<void ()>)'
/usr/local/include/webrtc/rtc_base/thread.h:335: undefined reference to `rtc::Thread::InvokeInternal(rtc::Location const&, rtc::FunctionView<void ()>)'
/usr/local/include/webrtc/rtc_base/thread.h:335: undefined reference to `rtc::Thread::InvokeInternal(rtc::Location const&, rtc::FunctionView<void ()>)'
/usr/local/include/webrtc/rtc_base/thread.h:335: undefined reference to `rtc::Thread::InvokeInternal(rtc::Location const&, rtc::FunctionView<void ()>)'
/usr/local/include/webrtc/rtc_base/thread.h:335: undefined reference to `rtc::Thread::InvokeInternal(rtc::Location const&, rtc::FunctionView<void ()>)'
CMakeFiles/test.dir/src/ice_gatherer.cpp.o:/usr/local/include/webrtc/rtc_base/thread.h:335: more undefined references to `rtc::Thread::InvokeInternal(rtc::Location const&, rtc::FunctionView<void ()>)' follow

**Comment by crow-misia** [comment]
What version (tag) of header file and .a file are you using?

The version of the header file you are using does not appear to match the .a file

**Comment by pengwang7** [comment]
I have checked and used the latest version, there is no such problem, thank you.
