### ISSUE TITLE
I ran into some trouble using it, used cricket::PortAllocator::SetConfiguration

### ISSUE THREAD

**Issue by pengwang7** [crow-misia/libwebrtc-bin#7]
Env:
Linux VM-0-7-centos 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC) 

Used like this:
    port_alloctor_->SetConfiguration(
            cricket::ServerAddresses(), std::vector<cricket::RelayServerConfig>(),
            ICE_CANDIDATE_POOL_SIZE, webrtc::NO_PRUNE);

The CMakeFile like this:
           
project(media_server C CXX)

set(CMAKE_BUILD_TYPE "Release")

#-Woverloaded-virtual
set(CXX_FLAGS
    -g
    -DCHECK_PTHREAD_RETURN_VALUE
    -D_FILE_OFFSET_BITS=64
    -DWEBRTC_POSIX
    -Wall
    -Wextra
    -Werror
    -Wconversion
    -Wno-unused-parameter
    -Wpointer-arith
    -Wwrite-strings
    -march=native
    -fno-omit-frame-pointer
    -std=c++17
    -rdynamic
    -lpthread
    #-fsanitize=address
    -lm
)
string(REPLACE ";" " " CMAKE_CXX_FLAGS "${CXX_FLAGS}")

#set(CMAKE_CXX_FLAGS_DEBUG "-O0")
#set(CMAKE_CXX_FLAGS_RELEASE "-O0 -DNDEBUG") 
#set(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/bin)
#set(LIBRARY_OUTPUT_PATH ${PROJECT_BINARY_DIR}/lib)
#set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake;${CMAKE_MODULE_PATH}")

include_directories("/usr/local/include/webrtc")
include_directories("/usr/local/include/webrtc/third_party/abseil-cpp")

#include_directories(${PROJECT_SOURCE_DIR})
include_directories(${PROJECT_SOURCE_DIR}/src)
link_directories(${PROJECT_SOURCE_DIR}/home/pengwang/workspace/media_server/libwebrtc/lib)
set(
    BUTIL_SRC
    ${PROJECT_SOURCE_DIR}/src/test.cpp
)

add_executable(media_server ${BUTIL_SRC})

target_link_libraries(media_server /XXXX/media_server/libwebrtc/lib/libwebrtc.a)

0000000000000000 T _ZN6webrtc23PeerConnectionInterface16SetConfigurationERKNS0_16RTCConfigurationE
0000000000000000 T _ZN7cricket13PortAllocator16SetConfigurationERKSt3setIN3rtc13SocketAddressESt4lessIS3_ESaIS3_EERKSt6vectorINS_17RelayServerConfigESaISB_EEibPN6webrtc14TurnCustomizerERKN4absl8optionalIiEE
0000000000000000 T _ZN7cricket13PortAllocator16SetConfigurationERKSt3setIN3rtc13SocketAddressESt4lessIS3_ESaIS3_EERKSt6vectorINS_17RelayServerConfigESaISB_EEiN6webrtc15PortPrunePolicyEPNSG_14TurnCustomizerERKN4absl8optionalIiEE
                 U _ZN7cricket13PortAllocator16SetConfigurationERKSt3setIN3rtc13SocketAddressESt4lessIS3_ESaIS3_EERKSt6vectorINS_17RelayServerConfigESaISB_EEiN6webrtc15PortPrunePolicyEPNSG_14TurnCustomizerERKN4absl8optionalIiEE
0000000000000aea r .L__FUNCTION__._ZN6webrtc14PeerConnection16SetConfigurationERKNS_23PeerConnectionInterface16RTCConfigurationE
0000000000000000 b _ZGVZN6webrtc14PeerConnection16SetConfigurationERKNS_23PeerConnectionInterface16RTCConfigurationEE32trace_event_unique_catstatic1760
0000000000000000 t _ZN3rtc12FunctionViewIFvvEE11CallVoidPtrIZN6webrtc14PeerConnection16SetConfigurationERKNS4_23PeerConnectionInterface16RTCConfigurationEE3$_8EEvNS2_9VoidUnionE
0000000000000000 T _ZN6webrtc14PeerConnection16SetConfigurationERKNS_23PeerConnectionInterface16RTCConfigurationE
                 U _ZN7cricket13PortAllocator16SetConfigurationERKSt3setIN3rtc13SocketAddressESt4lessIS3_ESaIS3_EERKSt6vectorINS_17RelayServerConfigESaISB_EEiN6webrtc15PortPrunePolicyEPNSG_14TurnCustomizerERKN4absl8optionalIiEE
0000000000000000 b _ZZN6webrtc14PeerConnection16SetConfigurationERKNS_23PeerConnectionInterface16RTCConfigurationEE32trace_event_unique_catstatic1760
00000000000002dc r .L__FUNCTION__._ZN6webrtc31PeerConnectionProxyWithInternalINS_23PeerConnectionInterfaceEE16SetConfigurationERKNS1_16RTCConfigurationE
                 U _ZN6webrtc14PeerConnection16SetConfigurationERKNS_23PeerConnectionInterface16RTCConfigurationE
0000000000000000 W _ZN6webrtc31PeerConnectionProxyWithInternalINS_23PeerConnectionInterfaceEE16SetConfigurationERKNS1_16RTCConfigurationE

Error:
undefined reference to `cricket::PortAllocator::SetConfiguration(std::set<rtc::SocketAddress, std::less<rtc::SocketAddress>, std::allocator<rtc::SocketAddress> > const&, std::vector<cricket::RelayServerConfig, std::allocator<cricket::RelayServerConfig> > const&, int, webrtc::PortPrunePolicy, webrtc::TurnCustomizer*, std::optional<int> const&)'

In that file, only this function(SetConfiguration) not avaiable.
I think I made some mistakes, can't I use this library like this, Can you give me an opinion?

**Comment by crow-misia** [comment]
libwebrtc.a is compiled using c++14, so use "-std=c++14".

**Comment by crow-misia** [comment]
or

This error is caused by abseil (https://github.com/abseil/abseil-cpp/issues/264) and can be handled with the following workarounds. However, it is not guaranteed that it will work correctly.

```
#include <absl/base/config.h>
#undef ABSL_USES_STD_ANY
#undef ABSL_USES_STD_OPTIONAL
#undef ABSL_USES_STD_VARIANT
#undef ABSL_USES_STD_STRING_VIEW
```

**Comment by pengwang7** [comment]
I have solved the problem according to your tips. Thank you very much.
