### ISSUE TITLE
Release 91.4472.0.0  does not compile on Debian 10

### ISSUE THREAD

**Issue by glynj-bsquare** [crow-misia/libwebrtc-bin#9]
Hi, I downloaded the latest build and tried building for x86 linux.
The downloads all worked fine, but the compilation stage failed as several of the binaries that are built and then used require a later version of glibc than Debian stable uses. The Debian packages are all up to date as of 11 May 2021.

The log of the end of the output (attached) shows that the build used "protoc" from the webrtc-build directory, which requires GLIBCXX_3.4.26, but Debian stable has GLIBC-2.28.10. Is there a way to make sure the protoc (and potentially other binaries) are built for the host OS glibc?

[xfer.log](https://github.com/crow-misia/libwebrtc-bin/files/6457727/xfer.log)

**Comment by crow-misia** [comment]
TARGET_OS and TARGET_CPU can be set to empty.
As a result, `make -C build TARGET_OS= TARGET_CPU= linux-x64
and OS and CPU build target will become same as host.

However, I haven't tested it, so I don't know if it will work.

Alternatively, maybe using Docker is a good idea.
